In [1]:
import numpy as np

In [2]:
my_list = [1, 2, 3]
my_list

[1, 2, 3]

In [3]:
np.array(my_list)

array([1, 2, 3])

In [4]:
my_matrix = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [5]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
np.arange(0, 11, 2)

array([ 0,  2,  4,  6,  8, 10])

In [8]:
np.zeros(3)

array([0., 0., 0.])

In [9]:
np.zeros((5, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [10]:
np.ones(3)

array([1., 1., 1.])

In [11]:
np.ones((3, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [12]:
np.random.rand(2)

array([0.43313531, 0.0634717 ])

In [13]:
np.random.rand(5, 5)

array([[0.5737137 , 0.72740407, 0.09032983, 0.64760911, 0.9910195 ],
       [0.33483659, 0.68120274, 0.26327402, 0.36791949, 0.68083955],
       [0.02997214, 0.25984813, 0.44874554, 0.333837  , 0.75761171],
       [0.8438658 , 0.82904802, 0.80377755, 0.38403378, 0.07995628],
       [0.22936811, 0.73245752, 0.62244322, 0.27916122, 0.67579745]])

In [14]:
np.random.randn(2)

array([1.51004085, 0.39981553])

In [16]:
np.random.randn(5, 5)

array([[ 1.49924569,  1.34051704,  0.01187733,  1.18471838, -0.40792326],
       [ 1.81224845,  0.58172456,  0.96542941,  0.20250392, -0.87483006],
       [-0.04430617, -1.34935024,  0.44649295, -1.02907684,  0.66517432],
       [-0.34724755, -0.27725328, -0.19795687,  0.57523789, -0.28726171],
       [-0.03499837, -1.05833348, -0.51845284,  1.16017129, -0.93014488]])

In [17]:
np.random.randint(1, 100)

79

In [18]:
arr = np.arange(0, 25)

In [19]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [20]:
arr.reshape(5, 5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [21]:
arr = np.array([10, 12, 41, 17, 49, 2, 46, 3, 19, 39])

In [22]:
print(arr.max())

49


In [23]:
print(arr.argmax())

4


In [24]:
print(arr.min())

2


In [25]:
print(arr.argmin())

5


In [26]:
arr.shape

(10,)

In [27]:
arr.reshape(2, 5)

array([[10, 12, 41, 17, 49],
       [ 2, 46,  3, 19, 39]])

In [28]:
arr.reshape(2, 5). shape

(2, 5)

In [30]:
arr = np.arange(0, 11)
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10]


In [31]:
arr[8]

8

In [32]:
arr[1:5]

array([1, 2, 3, 4])

In [33]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [34]:
arr = np.arange(0, 11)

In [35]:
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10]


In [36]:
slice_of_arr = arr[0:6]

In [37]:
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [38]:
slice_of_arr[:] = 99

In [39]:
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [40]:
arr_copy = arr.copy()
arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [41]:
arr_2d = np.array(([5, 10, 15], [20, 25, 30], [35, 40, 45]))

In [42]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [43]:
arr_2d[1]

array([20, 25, 30])

In [44]:
arr_2d[1, 0]

20

In [45]:
arr_2d[:2, 1:]

array([[10, 15],
       [25, 30]])

In [46]:
arr_2d[2, :]

array([35, 40, 45])