In [48]:
import pandas as pd

In [49]:
import numpy as np

In [50]:
from sklearn.model_selection import train_test_split

In [51]:
from sklearn.tree import DecisionTreeClassifier

In [52]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

In [53]:
df = pd.read_csv('iris_data_with_missing_values.csv', header = None)

In [54]:
df.columns = ['Sepal_Length', 'Sepal_Width', 'Petal_Length', 'Petal_Width', 'Class']
df.head(5)

Sepal_Length  Sepal_Width  Petal_Length  Petal_Width        Class
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

In [55]:
list = ['Sepal_Length', 'Sepal_Width', 'Petal_Length', 'Petal_Width']

In [56]:
for i in list:
    mean = df[i].mean()
    sd = df[i].std()
    df[i] = (df[i] - mean) / sd

In [79]:
df['Class'].fillna('missing', inplace = True)
df.fillna(df.mean(), inplace = True)

C:\Users\UDAYMI~1\AppData\Local\Temp/ipykernel_7732/2585824269.py:2: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  df.fillna(df.mean(), inplace = True)


In [80]:
X = df[df.columns[:-1]]
X

Sepal_Length   Sepal_Width  Petal_Length  Petal_Width
0       -0.724647  2.946098e-01     -1.337992    -1.298154
1       -0.903828 -1.131834e-01     -1.337992    -1.298154
2       -1.083009  4.993387e-02     -1.392902    -1.298154
3       -1.172599 -3.162479e-02     -1.283083    -1.298154
4       -0.814237  3.761685e-01     -1.337992    -1.298154
..            ...           ...           ...          ...
145      0.708801 -1.131834e-01      0.748559     1.435357
146      0.350439 -5.209767e-01      0.638740     0.914689
147      0.529620 -1.131834e-01      0.748559     1.044856
148      0.260848  2.130512e-01      0.858377     1.435357
149     -0.007923 -9.910817e-16      0.693649     0.784521

[150 rows x 4 columns]

In [81]:
Y = df['Class']

In [82]:
Y

0         Iris-setosa
1         Iris-setosa
2         Iris-setosa
3         Iris-setosa
4         Iris-setosa
            ...      
145    Iris-virginica
146    Iris-virginica
147    Iris-virginica
148    Iris-virginica
149    Iris-virginica
Name: Class, Length: 150, dtype: object

In [83]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.20, random_state = 30)

In [85]:
dtree = DecisionTreeClassifier()

In [93]:
dtree.fit(X_test, Y_test)

DecisionTreeClassifier()


In [91]:
predictions = dtree.predict(X_test)
predictions

array(['Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-virginica',
       'missing', 'Iris-versicolor', 'Iris-virginica', 'Iris-virginica',
       'Iris-versicolor', 'Iris-virginica', 'Iris-setosa',
       'Iris-virginica', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-setosa', 'Iris-versicolor', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-versicolor', 'Iris-virginica', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-virginica', 'Iris-virginica',
       'Iris-versicolor', 'Iris-virginica', 'Iris-setosa',
       'Iris-versicolor'], dtype=object)

In [88]:
print(classification_report(Y_test, predictions))

                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        12
Iris-versicolor       1.00      1.00      1.00         8
 Iris-virginica       1.00      1.00      1.00         9
        missing       1.00      1.00      1.00         1

       accuracy                           1.00        30
      macro avg       1.00      1.00      1.00        30
   weighted avg       1.00      1.00      1.00        30



In [89]:
print("Confusion Matrix")
print(confusion_matrix(Y_test, predictions))

Confusion Matrix
[[12  0  0  0]
 [ 0  8  0  0]
 [ 0  0  9  0]
 [ 0  0  0  1]]


In [90]:
print("Accuracy")
print(accuracy_score(Y_test, predictions))

Accuracy
1.0


In [94]:
import matplotlib.pyplot as plt

In [98]:
from sklearn import tree
fig, axes = plt.subplots(nrows = 1, ncols = 1, figsize = (16, 16), dpi = 1024)
tree.plot_tree(dtree)
fig.savefig('decision_tree.png')